#!/bin/zsh
# Regenerates ShimJS.swift from the canonical extensions/ultracmd-shim.js.
# The JS is emitted as ~200-line chunks (a single multi-hundred-KB literal
# trips a swift-frontend IRGen segfault) that are joined at runtime.
# Usage: ./scripts/embed-shim.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JS="$ROOT/Sources/ultracmd/extensions/ultracmd-shim.js"
OUT="$ROOT/Sources/ultracmd/extensions/ShimJS.swift"

if grep -q '"""#' "$JS"; then
  echo "shim JS contains raw-string terminator; aborting" >&2
  exit 1
fi

{
  print '// Generated by scripts/embed-shim.sh from ultracmd-shim.js — do not edit directly.'
  print 'enum ShimJS {'
  awk '
    BEGIN { chunk = 0; lines = 0 }
    NR == 1 { chunk++; print "    static let part" chunk " = #\"\"\"" }
    { print "    " $0; lines++ }
    lines >= 200 { print "    \"\"\"#"; chunk++; lines = 0; print "    static let part" chunk " = #\"\"\"" }
    END { if (lines > 0) print "    \"\"\"#" }
  ' "$JS"
  print ''
  print '    static let source: String = {'
  printf '        [' | cat
} > "$OUT"

# Build the join expression from the actual number of parts.
PARTS=$(grep -c 'static let part' "$OUT")
{
  for i in $(seq 1 "$PARTS"); do
    if [ "$i" -eq 1 ]; then printf 'part%d' "$i"; else printf ', part%d' "$i"; fi
  done
  printf '].joined()\n'
  print '    }()'
  print '}'
} >> "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, $PARTS parts)"
